### ISSUE TITLE
Cannot create image.  Results in HTTP error 413

### ISSUE THREAD

**Issue by inkysea** [vmware/photon-controller#24]
When creating a swarm or k8 image on .8 an http error 413 is returned.

photon image create ./photon-swarm-vm-disk1.vmdk -n photon-swarm-vm.vmdk -i EAGER
Using target 'http://192.168.110.41'
2016/04/18 12:08:52 Error: photon: HTTP 413: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.9.3</center>
</body>
</html>

I believe the 413 error may be caused by the nginx server not having client_max_body_size set appropriately.

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by molteanu** [comment]
inkysea: Thanks for reporting the issue. 
I have a quick follow on question: How large is the VMDK file you are trying to upload?

**Comment by inkysea** [comment]
It's the swarm vmdk.  It's about 240 MB.

**Comment by inkysea** [comment]
Any way I can change the setting in place?

**Comment by inkysea** [comment]
I updated the nginx.conf file in my environment's esxcloud/management_ui  container.
I added the following line to the http section.  This disables the max size.

 client_max_body_size 0;

Note that you may not want to completely disable the max body size, but will need to have an appropriate value to allow for various VMDKs.

**Comment by julykobe** [comment]
I met the same problem and I also updated the nginx.conf in esxcloud/installer_ui container on installer vm to resolve that.(Use mesos image).

**Comment by mwest44** [comment]
I'm a bit confused.  What does nginx have to do with the image upload?  Nginx is running in the UI container and is the webserver for the management and Installation UIs.  Have you verified that there is space available on your shared image datastore - and also on all of the other datastores connected to your cloud hosts.  Keep in mind that - EAGER flag means that we will copy this image to all disks so that there is a local copy no matter where VM/disk placement is done.  We have changed how the sync/replication process works, so I'm not completely sure when/how an error to replicated disk is returned.    Does your error come back immediately or is it later on during replication?   If you send me the management-api and housekeeper logs, I will take a look.

**Comment by inkysea** [comment]
Nginx is acting as the proxy for the Photon Controller api.   If nginx doesn't like the body size then the request never gets processed by the API.

**Comment by mwest44** [comment]
Maybe this is an area where I'm knowledge deficient.  The LB that proxies API-FE requests is HA-Proxy.  Where does nginx fit in?

**Comment by mwest44** [comment]
So I think this is the problem:   The image create command you used does not contain a port:  Using target 'http://192.168.110.41'
So it defaults to port 80, which is the management UI.  The management Ui is proxied by nginx.
API-FE runs on port 9000, or if you want to go through the load balancer, port 28080.  In that case you will not see nginx in the path.

**Comment by inkysea** [comment]
I think most prod environments would use a load balanced environment.  Good to know that I can connect to different ports.  Perhaps the CLI documentation should be updated to educate the users on the various port options

**Comment by kmjung** [comment]
We just took a fix for this issue for v0.9.
