### ISSUE TITLE
Running Photon after building from Building from source

### ISSUE THREAD

**Issue by uvgroovy** [vmware/photon-controller#38]
I am playing around with photon source code and trying to run my modified code. 

I am not sure how to update the installed photon OVA with the modified code.

I have the jars built and the docker container built, but i am not sure how to get them to run on the vm that I deployed using the installer-vm.ova

I didn't find it documented anywhere (here and in the google group). Can someone please add the relevant documentation for that?

I think this will help the community contribute code as they will be able to better test it.

Thanks!

**Comment by schadr** [comment]
if you deployed everything through the installer the only way right now is to copy all the bits into the container and restart the container.

- scp tar from the ``gradlew distTar`` command onto the vm
- copy the tar into the container (I usually just place it in the log folder since that is mounted)
- remove all jars in ``/usr/lib/esxcloud/$servicename/lib``
- extract tar file into ``/usr/lib/esxcloud/$servicename``

otherwise for development we usually rely on the devbox and use that as our "management plane"

**Comment by uvgroovy** [comment]
Seems to work, thanks!
