### ISSUE TITLE
Upgrade howto

### ISSUE THREAD

**Issue by gregorkistler** [vmware/photon-controller#42]
Hi,

I couldn´t find anything yet about:

> Upgrade – We’ve built a robust and seamless upgrade process ensuring that you can upgrade to v0.8 (and subsequent releases) with ease. If you’ve ever upgraded a distributed cloud platform you’re likely familiar with the significant pain points. The Photon Controller upgrade process incurs minimal downtime (as short as several minutes) and can be performed in a handful of CLI commands or API calls.

Can someone please give some hints about what the 

> handful of CLI commands or API calls

 are? :)
Thank you.

**Comment by mwest44** [comment]
We are still a little short on documentation - pre-GA.  
I have not tested it since the 0.8 release build, but this is what worked then- with a couple of changes based on the control plane starting in Paused mode.
(Basically we need to pause background processes that would clean up images during the migration.  Systems now deploy in paused mode. Not the case in earlier builds.)

Check the CLI help for specific command syntax.

This is the basic upgrade process:
You have an existing deployment I'll call production.
You will deploy a new instance of the control plane.  Call it upgrade environment.
photon target set "Your Upgrade Environment Endpoint"
photon system migration prepare "your Production Environment endpoint"
This starts the migration of meta data from the Production environment to your new Upgrade environment.  Production is still fully functional during this process.

photon system migration finalize "your Production Environment endpoint"
 During this phase "Production" is unavailable as we finalize the cut over and install the Agent VIBs on the hosts.

photon deployment resume_system deployment_id    #Starts background tasks

photon system migration status

**Comment by gregorkistler** [comment]
Alright, thank you.
Already thought about that, just wasn´t sure if that´s the way to go.
Will close the issue then.
