### ISSUE TITLE
UI to create flavors

### ISSUE THREAD

**Issue by govint** [vmware/photon-controller#56]
When a new tenant is created a ticket is also created. But then there is no way to create a flavor in the UI, Can this be added

**Comment by AlainRoy** [comment]
In Photon Controller 1.1, we didn't have time add flavor management to the UI. It is likely to be in Photon Controller 1.2. I'm going to close this request because it's already in our backlog of features to add. 

As a workaround, the flavor can be created via the command-line or API. 

Please note that today, flavors are not tied to tenants.
