### ISSUE TITLE
Deploy the Work Flow to a Real ESXi Server?

### ISSUE THREAD

**Issue by jeromeh66** [vmware/photon-controller#7]
Since the dev box is currently broken due to the Xenon issue, I would like to try out Photon Controller work flow on a real ESXi server (my laptop doesn't have enough RAM). I probably can set up an internal vSwitch to get around the IP address issue, but would like to know how I can change the IP address for the various services in Zookeeper, so that I can do without the internal vSwitch. 

Also, the Photon Controller CLI tool is for Mac and Windows only, is it possible to make a Linux version of the CLI tool that runs on Photon OS itself? So that I can run the CLI tool on the Photon Controller VM itself, to make it work in the deployment scenario described above?

**Comment by schadr** [comment]
before you run "vagrant up" to start devbox you will need to set some environment variables in order to give your devbox and network address that is reachable from the ESXi host you want to be using.

- PUBLIC_NETWORK_IP - your devbox ip
- PUBLIC_NETWORK_NETMASK
- PUBLIC_NETWORK_GATEWAY
- BRIDGE_NETWORK - the network adapter used by vagrant

once your devbox is up and running you need to switch to the ruby/integration_tests folder to actually add your ESXi host.
Set the following environment variable (see https://github.com/vmware/photon-controller/blob/master/ruby/integration_tests/Rakefile):
- ESX_DATASTORE - this is the datastore we will use to upload images to and create vms on
- ESXCLOUD_CHAIRMAN_IP - this is your PUBLIC_NETWORK_IP
- ESX_VM_PORT_GROUP - the port group your vms should be running on
- ESX_USERNAME - username of your ESXi host
- ESX_PASSWORD - password of you ESXi host
- ESX_IP - ip of your ESXi host

then run
```
rake cloudstore:seed
rake api:seed:host
```

**Comment by jeromeh66** [comment]
Thanks, I got it working with the End User Work Flow on a real ESXi server hosting both an ESXi VM and the Photon Controller VM.
