### ISSUE TITLE
k8s deployment failed with fatal_error

### ISSUE THREAD

**Issue by RedDevil69** [vmware/photon-controller#82]
Photon 1.1.0 with SSO
kubernetes-1.4.3-pc-1.1.0-5de1cb7.ova
Simple installation with one worker.

/photon cluster show 7b9b91dc-7bac-4162-8731-a09d45d5c9b5
Cluster ID:             7b9b91dc-7bac-4162-8731-a09d45d5c9b5
  Name:                 ks0cluster
  State:                FATAL_ERROR
  Type:                 KUBERNETES
  Worker count:         1
  Error Reason:         MultiException[java.lang.IllegalStateException: VmProvisionTaskService failed for clusterID 7b9b91dc-7bac-4162-8731-a09d45d5c9b5 with error VM failed to acquire an IP address. /photon/clustermanager/vm-provision-tasks/1a2b6b89545a510f76b61]
  Extended Properties:  map[client_windows_amd64_url:https://storage.googleapis.com:443/kubernetes-release/release/v1.4.3/bin/windows/amd64/kubectl netmask:255.255.240.0 cluster_ui_url:http://100.64.144.41:8080/ui master_ip:100.64.144.41 cluster_version:v1.4.3 client_windows_386_url:https://storage.googleapis.com:443/kubernetes-release/release/v1.4.3/bin/windows/386/kubectl dns:8.8.8.8 client_linux_386_url:https://storage.googleapis.com:443/kubernetes-release/release/v1.4.3/bin/linux/386/kubectl client_linux_amd64_url:https://storage.googleapis.com:443/kubernetes-release/release/v1.4.3/bin/linux/amd64/kubectl container_network:10.2.0.0/16 etcd_ips:100.64.144.42 gateway:100.64.144.1 client_darwin_amd64_url:https://storage.googleapis.com:443/kubernetes-release/release/v1.4.3/bin/darwin/amd64/kubectl]

VM ID                                 VM Name                                      VM IP
62a94a30-795e-48a6-8fef-2cfb3c324a82  master-244a5185-67f2-4cba-85a4-681cafe7cc6e  100.64.144.41
a2d6a551-a268-4c02-8e88-b78dd1ff7c92  etcd-ac69967c-1ccd-47c5-aec9-2d2cfbc05c20    100.64.144.42

./photon cluster list_vms 7b9b91dc-7bac-4162-8731-a09d45d5c9b5
ID                                    Name                                         State
62a94a30-795e-48a6-8fef-2cfb3c324a82  master-244a5185-67f2-4cba-85a4-681cafe7cc6e  STARTED
7bd565e6-82af-4a3b-81db-40da9a0b2fcb  worker-1225ca2d-b82d-49a5-b370-8d7fd92066cb  STARTED
a2d6a551-a268-4c02-8e88-b78dd1ff7c92  etcd-ac69967c-1ccd-47c5-aec9-2d2cfbc05c20    STARTED

**Comment by RedDevil69** [comment]
SP: I created network with CLI and marked it as default

**Comment by AlainRoy** [comment]
This is unfortunately one of the harder problems to diagnose. :( It's hard because we don't have good logging on VMs that fail to come up properly. We could imagine getting logging from a serial port, but that type of functionality doesn't yet exist in Photon Controller. 

For the IP addresses you chose (100.64.144.41 & 42), are those valid, unused addresses on your network? Have you tried deploying a cluster multiple types, but not fully cleaned up the previous VMs? (This could cause IP address conflicts.)

What version of ESXi are you using?

Do you have access to the ESXi web interface, so you can log into the console of the failed VM?

**Comment by fawadkhaliq** [comment]
@RedDevil69 can you confirm if this failed on the worker node provisioning? I assume yes, because its a serial deployment in order etcd->master->worker(s). If its the worker, I believe there is an expectation to have DHCP server enabled on the network for the worker nodes to acquire IP addresses. If you do not have a DHCP server running and accessible from the network, where worker node boots up, you will run into this issue. The cluster create will wait until it fails because of VM not getting an IP address. 

If the DHCP server is not running, then please go ahead and enable it. That will solve you problem. Otherwise, more information might help as @AlainRoy suggested.

**Comment by RedDevil69** [comment]
No DHCP in this "VM Network".
Maybe that is the problem ?

**Comment by RedDevil69** [comment]
@fawadkhaliq is there any dhcp role inside photon architecture or should I deploy something on my own ?

**Comment by mwest44** [comment]
When using standard esxi networking, you must provide your own dhcp service.  In the 1.2 release, we will provide a dhcp appliance as part of our support for NSX.  This is an interim solution until NSX-T provides integrated DHCP later this year.

**Comment by fawadkhaliq** [comment]
@RedDevil69 Yes, that is the problem you ran into. Currently, there is no alternative to it as cluster deployment does not take static IPs for workers nodes (I think its by design since workers can scale in/out, having static would mean a pool of IPs will have to be maintained, DHCP is simpler definitely).

**Comment by RedDevil69** [comment]
@fawadkhaliq , @mwest44 in download section there is dhcp-ova-5de1cb7.ova
What for ?

**Comment by mwest44** [comment]
That is the ova appliance I mentioned.  You can download it and manually set up dhcp on your network.  No support/doc for that at this point though.

**Comment by AlainRoy** [comment]
@RedDevil69: That OVA appliance is meant for us with NSX. While you may be able to use it without NSX, we haven't tried it or documented how to use it. Most datacenters already have DHCP available, so that wasn't a use case we were concerned with.

**Comment by AlainRoy** [comment]
@fawadkhaliq: You are correct: we prefer DHCP for worker nodes because it's much simpler for users.

**Comment by RedDevil69** [comment]
@AlainRoy @mwest44 I deployed my own dhcp and now works perfectly. K8S up an running. Scalling is fine as well.
Worth to add that as an optional requirement to the installation of the Photon Platform

**Comment by AlainRoy** [comment]
Great--glad to hear it!

**Comment by rushins** [comment]
hello i get FATAL_ERROR during kubernetes deploy with Photon 1.2. does this mean with DHCP related. the wonder part is i can ping the master, workers IP address and load balancer IP but cluster creation at the end comes "FATAL_ERROR"

Any clue
